### ISSUE TITLE
Would you consider working with json here?

### ISSUE THREAD

**Issue by steinmetz** [IxTzy/Interaktionskonzept#2]
Hi, 
What do you think if we would use JSON for communication?

then it would be easier to see which information will be sent... do you have free time this week or you have a lot of things to do already?

https://github.com/IxTzy/Interaktionskonzept/blob/1ca98a48e698c9cab8bed8e62ca691d2837bf453/Implementierung/Release%200.3/register.py#L75

**Comment by IxTzy** [comment]
I'm sorry, i didnt saw this until now... So I dont think that I can change that by tomorow..

**Comment by steinmetz** [comment]
no problem... tomorrow we talk, I think now it is better to let like this :)
